### ISSUE TITLE
📝ジョーカーの扱いが分からない

### ISSUE THREAD

**Issue by mikami-shugo-fixer** [miyaji-yusei-fixer/seven#1]
遊び方の説明にジョーカーの扱いが書いて無いように感じたのでお手すきで確認お願いします

**Comment by miyaji-yusei-fixer** [comment]
確かに...
改めて遊び方とチュートリアルに記載するけどジョーカーは0扱いです
なので引ければラッキーなカードです
CPUは積極的にジョーカーを捨てるように設定してるので、捨て札に出たら積極的に拾うことをおススメします
